---
name: Deploy docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material["imaging"]
      - run: pip install mkdocs
      - run: pip install "pymdown-extensions>=10.11.2, <11"
      - run: pip install "mkdocs-glightbox>=0.4.0, <0.5"
      - run: pip install "mkdocs-open-in-new-tab>=1.0.5, <2"
      - run: pip install "mkdocs-macros-plugin>=1.2.0, <2"
      - run: pip install omegaconf
      - name: Build site
        run: mkdocs build
      - name: Deploy to GitHub pages
        run: mkdocs gh-deploy --force
